robot_state_publisher:
  ros__parameters:
    robot_description: |
      <?xml version="1.0"?>
      <robot name="test_robot" xmlns:xacro="http://ros.org/wiki/xacro">
        <material name="grey"><color rgba="0.6 0.6 0.6 1.0"/></material>

        <link name="base_link">
          <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1.0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
          </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry><box size="0.2 0.2 0.05"/></geometry>
            <material name="grey"/>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry><box size="0.2 0.2 0.05"/></geometry>
          </collision>
        </link>

        <link name="link1">
          <inertial>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
          </inertial>
          <visual>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <geometry><box size="0.05 0.2 0.2"/></geometry>
            <material name="grey"/>
          </visual>
          <collision>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <geometry><box size="0.05 0.2 0.2"/></geometry>
          </collision>
        </link>

        <joint name="hinge_joint" type="revolute">
          <parent link="base_link"/>
          <child  link="link1"/>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
          <limit lower="-1.57" upper="1.57" effort="10.0" velocity="2.0"/>
          <dynamics damping="0.1" friction="0.0"/>
        </joint>

        <ros2_control name="GazeboSystem" type="system">
          <hardware><plugin>gazebo_ros2_control/GazeboSystem</plugin></hardware>
          <joint name="hinge_joint">
            <command_interface name="position"/>
            <state_interface   name="position"/>
            <state_interface   name="velocity"/>
          </joint>
        </ros2_control>

        <gazebo>
          <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>/home/wintunlatt/ws_ros2/install/test_control/share/test_control/config/test_controllers.yaml</parameters>
          </plugin>
        </gazebo>
      </robot>
